use coreappdb;

CREATE TABLE customer_sale (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  customer INT NOT NULL,
  sale INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  FOREIGN KEY (customer) REFERENCES customers(id),
  FOREIGN KEY (sale) REFERENCES sales(id)
);